spring.application.name=adanext2

# H2 Console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:adanext
spring.datasource.driverClassName=org.h2.Driver

# Désactive Security temporairement
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
